# writes font_data.cpp from the fonts in assets/, so the ui never parses font files from disk at runtime
# rerun after changing a font: cmake -P ui/resources/embed_fonts.cmake
set(root ${CMAKE_CURRENT_LIST_DIR}/../..)
set(fonts
    poppins_regular=assets/Poppins-Regular.ttf
    poppins_bold=assets/Poppins-Bold.ttf
)

set(out "// generated by ui/resources/embed_fonts.cmake from assets/, don't edit by hand\n\nnamespace celosia::resources::font_data {\n")
foreach(entry ${fonts})
    string(REPLACE "=" ";" entry ${entry})
    list(GET entry 0 name)
    list(GET entry 1 path)

    file(READ ${root}/${path} hex HEX)
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n        " bytes "${bytes}")
    string(STRIP "${bytes}" bytes)

    string(APPEND out "    // ${path}\n    extern const unsigned char ${name}[] = {\n        ${bytes}\n    };\n    extern const int ${name}_size = sizeof(${name});\n\n")
endforeach()
string(REGEX REPLACE "\n\n$" "\n}\n" out "${out}")

file(WRITE ${CMAKE_CURRENT_LIST_DIR}/font_data.cpp "${out}")
